import { Badge, Text } from "@mantine/core";
import { IconArrowRight, IconDiamond, IconStar } from "@tabler/icons";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import { Footer, Header, Testimonial } from "../components";
import { useQuery } from "urql";
import "react-responsive-carousel/lib/styles/carousel.min.css"; // requires a loader
import { Carousel } from "react-responsive-carousel";

export default function Home() {
  const router = useRouter();

  const GET_SECTIONS = `
      query GET_SECTIONS(
        $page : String
      ){
        getSections(page: $page){
          id
          value
          identifier
        }
      }
  `;

  const [{ data, fetching, error }] = useQuery({
    query: GET_SECTIONS,
    variables: { page: "home" },
  });

  if (fetching) return <p>Loading ....</p>;
  if (error) return <p>error...</p>;

  console.log(data?.getSections);

  return (
    <div>
      <Head>
        <title>Serene Products & Services</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header section */}
      <Header active="home" />

      <main>
        <Slider />

        <WhoWeAre value={data?.getSections[0]} />
        <Principles
          mission={data?.getSections[1]?.value}
          vision={data?.getSections[2]?.value}
          core_values={data?.getSections[3]?.value}
        />
        <MiniProducts />
        <Clients />
        <Testimonials />
        <Partners />
      </main>

      {/* Footer */}
      <Footer />
      <div className="sticky float-right bottom-6 right-6">
        <a
          onClick={() => {
            router.push(
              `https://wa.me/254713763057?text=Hello%2CI%20would%20like%20to%20enquire%20about%20this%20product%20%3A%20http%3A%2F%2Flocalhost%3A3000%2Fproduct%2F${data?.id}`
            );
          }}
        >
          <img src="/whatsapp.png" alt="whatsapp" className="w-[48px]" />
        </a>
      </div>
    </div>
  );
}

const Slider = () => {
  return (
    <div>
      <Carousel autoPlay infiniteLoop showThumbs={false}>
        <div>
          <img
            src={`/sliders/1.png`}
            alt="cover"
            className="object_cover w-full "
          />
        </div>
        <div>
          <img
            src={`/sliders/2.png`}
            alt="cover"
            className="object_cover w-full "
          />
        </div>
        <div>
          <img
            src={`/sliders/3.png`}
            alt="cover"
            className="object_cover w-full "
          />
        </div>
      </Carousel>
    </div>
  );
};

const WhoWeAre = ({ value }) => {
  return (
    <div className="p-6 pl-12">
      <div className="md:flex">
        <div className=" w-full md:w-1/2">
          <p className="tracking-wide uppercase text-[1.2rem] text-black font-extrabold inline ">
            Who we are
          </p>
          <div className="w-[100px] h-[4px] bg-[#d32131] mb-8" />
          <p className="text-[0.9rem] text-gray-600 font-[300]">
            {value?.value}
          </p>
          {/* <p className="text-[0.9rem] text-gray-600 font-[300]">
            Serene products and servicing deals with sale, servicing and
            maintenance of fire engineering systems, generators, solar,
            electrical, safety audits and trainings.
          </p>
          <br />
          <p className="text-[0.9rem] text-gray-600 font-[300]">
            We offer high quality fire products that are manufactured to
            international standards such as :
          </p>
          <br />
          <div className="space-y-2">
            <span className="block text-gray-800 text-[0.9rem]">
              <IconStar
                fill="#d32131"
                stroke={0}
                size={12}
                className="inline mr-4"
              />
              British Standards (BS)
            </span>
            <span className="block text-gray-800 text-[0.9rem]">
              <IconStar
                fill="#d32131"
                stroke={0}
                size={12}
                className="inline mr-4"
              />
              European Standards (BS)
            </span>
            <span className="block text-gray-800 text-[0.9rem]">
              <IconStar
                fill="#d32131"
                stroke={0}
                size={12}
                className="inline mr-4"
              />
              Underwriter Laboratory Standards
            </span>
            <span className="block text-gray-800 text-[0.9rem]">
              <IconStar
                fill="#d32131"
                stroke={0}
                size={12}
                className="inline mr-4"
              />
              Kenya Bureau of Standards (KEBS)
            </span>
          </div> */}
        </div>
        <div className=" w-full md:w-1/2">
          <img
            src="/fire-extig.jpg"
            alt="what_we_do_1"
            className="z-1  sm:w-4/5 w-full r-0"
          />
        </div>
      </div>
    </div>
  );
};

const Principles = ({ mission, vision, core_values }) => {
  return (
    <div className="w-4/5 mx-auto bg-yellow-400 p-6 grid grid-cols-1 md:grid-cols-3 gap-12">
      <div className=" col-span-1 space-y-6">
        <span className="flex space-x-6">
          <h1 className="font-bold font-[Oswald]">01</h1>
          <span class="inline-block align-bottom mt-4 uppercase">Mission</span>
        </span>
        <p className="font-light text-[0.8rem] text-gray-600">
          {mission ||
            " Promoting and delivering fast, effective and comprehensive engineering solutions."}
        </p>
      </div>
      <div className="col-span-1space-y-6">
        <span className="flex space-x-6">
          <h1 className="font-bold font-[Oswald]">02</h1>
          <span class="inline-block align-bottom mt-4 uppercase">Vision</span>
        </span>
        <p className="font-light text-[0.8rem] text-gray-600">
          {vision ||
            "Generating and collaborating with customer to produce customers centric solutions."}
        </p>
      </div>
      <div className="col-span-1 space-y-6">
        <span className="flex space-x-6">
          <h1 className="font-bold font-[Oswald]">03</h1>
          <span class="inline-block align-bottom mt-4 uppercase">
            Core values
          </span>
        </span>
        <p className="font-light text-[0.8rem] text-gray-600">
          {core_values || " Innovation, excellence, passion."}
        </p>
      </div>
    </div>
  );
};

const MiniProducts = () => {
  const router = useRouter();
  const GET_FEATURED = `
      query GET_FEATURED{
        getFeatured{
          name
          image
          id          
        }
      }  
  `;

  const [{ data, fetching, error }] = useQuery({
    query: GET_FEATURED,
  });

  if (fetching) return <p>Loading ....</p>;
  if (error) return <p>Error ....</p>;

  return (
    <div className="mt-14  w-[90%] mx-auto mb-8">
      <p className="tracking-wide uppercase text-[1.2rem] text-black font-extrabold inline ">
        featured products
      </p>
      <div className="w-[144px] h-[4px] bg-[#d32131] mb-8" />
      <p className="text-[0.9rem] text-gray-600 mb-8">
        We supply, install and maintain fire safety equipments at discounted
        prices. Here are some of our top selling equipment.
      </p>
      <div className="flex space-x-4 overflow-x-auto ">
        {data?.getFeatured.map((product) => (
          <div
            key={product?.id}
            className="flex relative shadow-md px-5 space-x-4 min-w-[300px] max-w-[400px]  my-auto"
          >
            <img
              src={product?.image}
              style={{
                width: 100,
                height: 100,
              }}
              alt={`product_${product?.id}`}
            />
            <Badge
              color="green"
              size="md"
              radius={null}
              variant="filled"
              className="absolute left-0 top-0"
            >
              <p className="font-light">OFFER !</p>
            </Badge>
            <div className="my-auto">
              <Text lineClamp={3} fw="bolder">
                {product?.name}
              </Text>
              <div className="flex mb-3">
                {[1, 2, 3, 4, 5].map((el) => (
                  <IconStar
                    key={el}
                    fill="#FFD700"
                    stroke={0}
                    size={12}
                    className="inline"
                  />
                ))}
              </div>
              <a
                className="text-[#d32121] font-[300] uppercase text-[0.7rem]"
                href={`/product/${product?.id}`}
              >
                Learn more <IconArrowRight className="inline" size={12} />{" "}
              </a>
            </div>
          </div>
        ))}
      </div>

      <div className="w-full flex flex-row-reverse">
        <button
          onClick={() => router.push("/product")}
          className="uppercase text-[#d32121] font-[300] text-[0.8rem]"
        >
          see all products
        </button>
      </div>
    </div>
  );
};

const Clients = () => {
  return (
    <div className="mt-14  w-[90%] mx-auto mb-8">
      <p className="tracking-wide uppercase text-[1.2rem] text-black font-extrabold inline ">
        our clients
      </p>
      <div className="w-[85px] h-[4px] bg-[#d32131] mb-8" />
      <p className="text-[0.9rem] text-gray-600 mb-8">
        We have the trust of the biggest names in business
      </p>
      <div className="flex space-x-8 space-y-8"></div>
    </div>
  );
};

const Testimonials = () => {
  return (
    <div className="mt-14  w-[90%] mx-auto mb-8">
      <p className="tracking-wide uppercase text-[1.2rem] text-black font-extrabold inline ">
        Testimonials
      </p>
      <div className="w-[85px] h-[4px] bg-[#d32131] mb-8" />
      <div className=" mx-auto space-x-6 mt-6  grid grid-cols-1 md:grid-cols-3 gap-8">
        {[1, 2, 3].map((el) => (
          <Testimonial key={el} />
        ))}
      </div>
    </div>
  );
};

const Partners = () => {
  return (
    <div className="mt-14  w-[90%] mx-auto mb-8">
      <p className="tracking-wide uppercase text-[1.2rem] text-black font-extrabold inline ">
        Partners
      </p>
      <div className="w-[70px] h-[4px] bg-[#d32131] mb-8" />
      <div className="flex space-x-8 m-4 my-12">
        {[1].map((el) => (
          <img key={el} src="/finder.png" className="w-[120px]" />
        ))}
      </div>
    </div>
  );
};
